### PR TITLE
Log output of startup script. Fix typo.

### PR DESCRIPTION
**Pull request by jcass77**

### CODE REVIEW

**Comment by jcass77** [comment]
@kingosticks, this should make it easier to troubleshoot Pi MusicBox when running headless.

Adds the standard output and errors to a log file located at ```/var/log/musicbox_startup.log```.

Please consider adding to the main development branch? I did not have a monitor available to verify that the output is still being displayed to the on-screen console during the boot sequence (but it should be).

**Comment by kingosticks** [comment]
Alternatively we could install `bootlogd`. But this seems just as good. Probably also worth adding this log to https://github.com/woutervanwijk/Pi-MusicBox/issues/274 when we get around to that.
thanks

**Comment by jcass77** [comment]
I think using ```bootlogd``` will be much better - do we have an ability to install / update packages in the distribution or is this something that @woutervanwijk  will have to assist with?

It's probably worth updating the various Mopidy-related packages using PIP as well before the next release.

**Comment by kingosticks** [comment]
I am currently doing just that in a private branch. Just ironing out some
problems in the create_musicbox script that popped up. Will add bootlogd to
the changes and push it asap. I think the next release is going to need a
fair amount of testing.

**Pull request merged**
